Issue7 - Read a configuration file from command line
lambdaclass/libtorrent-rs pull request #21
Opened 2023-01-23 15:36 UTC by MarPinPar

Still working in the `Crate Clap` implementation

2023-01-24 22:18 UTC, juanbono requested changes

2023-01-24 22:18 UTC, juanbono commented on dtorrent/README.md
> +Then run the program with `cargo` followed by the directory containing the .torrent files and the directory containing the .cfg files:
the second parameter should be a single configuration file

2023-01-24 22:19 UTC, juanbono commented on dtorrent/README.md
> +Then run the program with `cargo` followed by the directory containing the .torrent files and the directory containing the .cfg files:
Also please fix the conflicts

2023-01-25 13:33 UTC, Oppen requested changes

2023-01-25 13:33 UTC, Oppen commented on README.md
> +A Rust implementation of the [BitTorrent V2] (http://bittorrent.org/beps/bep_0052.html) protocol. For now only V1 is implemented but we're working on V2.
```suggestion
A Rust implementation of the [BitTorrent V2](http://bittorrent.org/beps/bep_0052.html) protocol. For now only V1 is implemented but we're working on V2.
```
The format for links is `[test](link)`. That's just correct Markdown.

2023-01-27 15:43 UTC, juanbono approved these changes

2023-02-13 20:49 UTC, Oppen approved these changes

2023-02-14 15:02 UTC, merged